"""Executes the in-sandbox parsing script for real, outside the sandbox.

_SANDBOX_SCRIPT is a string. Nothing imports it, type-checks it, or runs it
in the normal test suite, so a typo or a wrong pypdfium2 call would surface
only inside a live Daytona box mid-demo — the worst possible place to find
it. These tests exec the actual script body against real documents and
assert on what it prints.

This is not a substitute for tests/test_referral_sandbox.py, which covers
the sandbox *lifecycle* with the SDK mocked. This covers the payload that
lifecycle carries.

Skipped when the rasterisation libraries are not installed locally: they are
dependencies of the sandbox image (see _parsing_image), not of the backend,
so a teammate without them should not see red.
"""

from __future__ import annotations

import base64
import io
import json

import pytest

from services.referral import sandbox as sb

pdfium = pytest.importorskip("pypdfium2", reason="sandbox-image dep, not a backend dep")
PIL_Image = pytest.importorskip("PIL.Image", reason="sandbox-image dep, not a backend dep")


def run_script(content: bytes, filename: str) -> dict:
    """Run the real script body the way code_run would, and parse its stdout."""
    script = sb._build_script(content, filename)
    printed: list[str] = []
    exec(compile(script, "<sandbox>", "exec"), {"print": printed.append})
    assert len(printed) == 1, f"script must print exactly one JSON line, got {len(printed)}"
    return json.loads(printed[0])


def make_pdf(pages: int = 1, text: str = "Rectal bleeding x3 weeks") -> bytes:
    """A minimal multi-page PDF built with pypdfium2's own writer."""
    doc = pdfium.PdfDocument.new()
    for _ in range(pages):
        doc.new_page(300, 400)
    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def make_png(size=(60, 40), colour=(255, 255, 255)) -> bytes:
    buf = io.BytesIO()
    PIL_Image.new("RGB", size, colour).save(buf, format="PNG")
    return buf.getvalue()


def is_png(raw: bytes) -> bool:
    return raw.startswith(b"\x89PNG\r\n\x1a\n")


# ---------------------------------------------------------------------------
# PDFs: the referral fax path
# ---------------------------------------------------------------------------


def test_pdf_is_rasterised_to_one_png_per_page():
    out = run_script(make_pdf(pages=3), "referral.pdf")
    assert len(out["images"]) == 3
    for encoded in out["images"]:
        assert is_png(base64.b64decode(encoded))


def test_rasterised_pages_are_readable_images_at_useful_resolution():
    """Scale must actually be applied — a checkbox at thumbnail size is not
    something a vision model can resolve."""
    out = run_script(make_pdf(pages=1), "referral.pdf")
    img = PIL_Image.open(io.BytesIO(base64.b64decode(out["images"][0])))
    width, height = img.size
    assert width >= 300 * sb.RASTER_SCALE * 0.9
    assert height >= 400 * sb.RASTER_SCALE * 0.9


def test_pdf_still_returns_text_alongside_images():
    """The existing text extractor depends on this; rasterisation is additive."""
    out = run_script(make_pdf(pages=1), "referral.pdf")
    assert "text" in out
    assert isinstance(out["text"], str)


def test_page_count_is_capped(monkeypatch):
    monkeypatch.setattr(sb, "MAX_RASTER_PAGES", 2)
    out = run_script(make_pdf(pages=5), "referral.pdf")
    assert len(out["images"]) == 2


def test_byte_budget_stops_rasterisation_rather_than_blowing_stdout(monkeypatch):
    monkeypatch.setattr(sb, "RASTER_BUDGET_BYTES", 10)  # smaller than any page
    out = run_script(make_pdf(pages=3), "referral.pdf")
    assert out["images"] == []
    # and the text path is untouched by the images being dropped
    assert isinstance(out["text"], str)


# ---------------------------------------------------------------------------
# uploaded images: the patient-history path
# ---------------------------------------------------------------------------


def test_uploaded_image_comes_back_as_a_page_image():
    out = run_script(make_png(), "insurance_card.png")
    assert len(out["images"]) == 1
    assert is_png(base64.b64decode(out["images"][0]))


def test_jpeg_upload_is_re_encoded_to_png():
    """Everything crossing back is generated by our own code, not carried in
    from the document — a hostile encoder payload does not survive the round
    trip through PIL."""
    buf = io.BytesIO()
    PIL_Image.new("RGB", (50, 50), (200, 10, 10)).save(buf, format="JPEG")
    out = run_script(buf.getvalue(), "scan.jpg")
    assert is_png(base64.b64decode(out["images"][0]))


# ---------------------------------------------------------------------------
# everything else fails safe
# ---------------------------------------------------------------------------


def test_plain_text_document_yields_text_and_no_images():
    out = run_script(b"REFERRAL: 42 y/o, rectal bleeding", "referral.txt")
    assert out["images"] == []
    assert "42 y/o" in out["text"]


def test_corrupt_pdf_yields_empty_output_not_a_crash():
    """Empty text is what pipeline.py already treats as unparseable ->
    ESCALATE. The script must never raise, or exit_code would be non-zero
    and the failure mode would be a sandbox error instead of a triage one."""
    out = run_script(b"%PDF-1.4 this is not actually a pdf", "broken.pdf")
    assert out["images"] == []
    assert out["text"] == ""


def test_corrupt_image_yields_empty_output_not_a_crash():
    out = run_script(b"\x89PNG\r\n\x1a\n garbage after the header", "broken.png")
    assert out["images"] == []


def test_script_always_prints_exactly_one_json_object():
    for content, name in [
        (make_pdf(), "a.pdf"),
        (make_png(), "b.png"),
        (b"plain", "c.txt"),
        (b"", "d.pdf"),
    ]:
        out = run_script(content, name)
        assert set(out) == {"text", "images"}


def test_document_bytes_cannot_break_out_of_the_preamble():
    """The payload is embedded as a JSON-escaped literal; a filename that
    looks like code must stay data."""
    hostile = '"; import os; os.system("echo pwned"); FILENAME = "x.txt'
    out = run_script(b"harmless", hostile)
    assert out["images"] == []
